# See https://github.com/scala-steward-org/scala-steward/blob/main/docs/repo-specific-configuration.md

pullRequests.frequency = "30 days"

buildRoots = [".", "example"]

pullRequests.grouping = [
  { name = "patches", title = "chore(deps): Patch updates", filter = [{ version = "patch" }] }
]
