name: Update Dependency Graph for SBT
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  dependency-graph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        id: checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install Scala
        uses: guardian/setup-scala@v1
      - name: Submit dependencies
        id: submit
        uses: scalacenter/sbt-dependency-submission@1cc96a7038ea2b014c200c1dae3a0cc92293b91d # v3.2.2
      - name: Log snapshot for user validation
        id: validate
        run: cat ${{ steps.submit.outputs.snapshot-json-path }} | jq
    permissions:
      contents: write